version: "3"
  
services:
  pingo:
    container_name: pingo
    image: zhanws/pingo:latest
    restart: always
    privileged: true
    devices:
      - /dev/snd
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - 5001:5001

